id = "mcfunction"
name = "mcfunction"
version = "0.0.1"
schema_version = 1
authors = ["Ben Heidemann <ben@heidemann.dev>"]
description = "Mcfunction support for Zed"
repository = "https://github.com/bcheidemann/zed-mcfunction"

[grammars.mcfunction]
repository = "https://github.com/IoeCmcomc/tree-sitter-mcfunction"
commit = "5bf1f08320697c24f395af76422a845f9f627fb0"
