name = "mcfunction"
grammar = "mcfunction"
path_suffixes = ["mcfunction"]
autoclose_before = "}])"
line_comments = ["# "]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
]
